Calculations
MatasLa/SmartSaver pull request #22
Opened 2020-10-13 15:45 UTC by DeividasLT5

Calculation reworks and improvements

2020-10-13 18:45 UTC, Stokalas requested changes
Eventhough everything seems to be fine I would really like to see response or changes to the parts of code where I commented. It is not neccesary but would improve code quality overall.

2020-10-13 18:45 UTC, Stokalas commented on SmartSaver/backend/DataCalculations.cs
> +                savedAmount += (data.Amount * (0.1M * percentage));
Shouldn't all these multiplication values be saved as Constants? Since if we wanted to change multiplier, we would have to change every single number instead of one constant.

2020-10-13 18:45 UTC, Stokalas commented on SmartSaver/backend/DataCalculations.cs
> +            OfferData newExpensesOffers = new OfferData(id, amount);
Not sure if you are using resharper, but when creating any type of variable if it's assigned on creation it's best to use 'var' instead of type

2020-10-13 18:45 UTC, Stokalas commented on SmartSaver/backend/DataCalculations.cs
> +                    temp = 1M;
These hardcoded numbers everywhere 🍌

2020-10-14 05:04 UTC, ciliakas requested changes
Completely agree with Gytis here, the hard coded numbers are not a good practice and should be changed. Other than that the code looks mostly neat and tidy, except I don't quite understand the name of method SwitchCalculation, maybe it could be more informative

2020-10-14 05:04 UTC, ciliakas commented on SmartSaver/utilities/Enums.cs
> +        Unnecesary
Typo, should be : unnecessary

2020-10-14 18:23 UTC, DeividasLT5 commented on SmartSaver/backend/DataCalculations.cs
> +                savedAmount += (data.Amount * (0.1M * percentage));
Good insight, I figured having "percentage" would be enough, but this should be integrated.

2020-10-14 18:24 UTC, DeividasLT5 commented on SmartSaver/backend/DataCalculations.cs
> +                    temp = 1M;
Will fix :)

2020-10-14 18:25 UTC, DeividasLT5 commented on SmartSaver/backend/DataCalculations.cs
> +            OfferData newExpensesOffers = new OfferData(id, amount);
Will look into installing it, thanks for the tip

2020-10-14 19:22 UTC, DeividasLT5 commented on SmartSaver/utilities/Enums.cs
> +        Unnecesary
Oops

2020-10-15 07:18 UTC, Stokalas approved these changes

2020-10-15 07:25 UTC, ciliakas approved these changes
Much much better, the only hard coded numbers I noticed where in the ChoosingImportance method.

2020-10-15 07:25 UTC, ciliakas commented on SmartSaver/backend/DataCalculations.cs
> +                    return ImportanceBasedCalculation(data, savedAmount, savingRatio * 4, entryType);
A big improvement so far, but maybe it would be possible to change these hardcoded numbers as well?

2020-10-16 08:46 UTC, merged