Dynamic monthly
MatasLa/SmartSaver pull request #28
Opened 2020-10-17 09:08 UTC by Stokalas

Only file to look at is MonthlyUpdater.cs

2020-10-17 17:59 UTC, ciliakas requested changes
Good idea and tidy implementation, hovewer some glitches need ironing out, highlighted in the comments

2020-10-18 13:48 UTC, Stokalas commented
Implemented changes according to the review, which by the way was very useful and pointed main problems, which has helped to solve some problems a lot quicker 🙂

2020-10-18 15:48 UTC, ciliakas approved these changes
Did some tests and the dynamic monthly adding now works! Also nice job with the improvements to efficiency in UpdateMonthlyIncome.
However I really think we need to clean up our Data class, as it is quite a mess now, with some methods affecting only the entries in the database and some affecting both the database and the local data

2020-10-18 15:48 UTC, ciliakas commented on SmartSaver/DataManagement/MonthlyUpdater.cs
> +        }
If we pass a DataFilter to Monthly Updater, wouldn't it make sense to take the Data object from DataFilter? Of course we'd need to create a getter for the DataFilter class

2020-10-18 15:48 UTC, ciliakas commented on SmartSaver/DataManagement/MonthlyUpdater.cs
> +                var todayDate = DateTime.Today.Date;
I think we could move the todayDate variable from the foreach loops since it's always the same

2020-10-18 15:48 UTC, ciliakas commented on SmartSaver/DataManagement/MonthlyUpdater.cs
> +            _data.EditIncomeItem(entry.Id, false);//Moved here since no point to edit in each cycle rotation
Very good change, especially considering at the moment every change involves the database and makes everything take up so much more time.

2020-10-18 15:48 UTC, ciliakas commented on SmartSaver/DataManagement/MonthlyUpdater.cs
> +                var todayDate = DateTime.Today.Date;
Could also move this calculation to TimeManager, so we can reuse it if we ever need to :)

2020-10-18 15:48 UTC, ciliakas commented on SmartSaver/DataManagement/Data.cs
>  			else
Now the editing seems to be working fine, though it would be nice to add this to every Edit method, though I know everything will be reworked soon so there is not much of a point to do this atm

2020-10-18 16:45 UTC, Stokalas commented on SmartSaver/DataManagement/MonthlyUpdater.cs
> +                var todayDate = DateTime.Today.Date;
Both good suggestions

2020-10-18 16:48 UTC, Stokalas commented on SmartSaver/DataManagement/MonthlyUpdater.cs
> +        }
I can see your point, but I would suggest providing required resources inside the handler, or wherever all these objects are created, to see some kind of "hierarchy", maybe I'm understanding it wrong, but I think this would make it easier to understand. On the other hand it would be still understandable if what you suggest would be inplemented. 
TLDR mixed feelings on that aspect

2020-10-18 17:18 UTC, ciliakas requested changes
Jumped the ship to soon and now found new errors :(

2020-10-18 17:18 UTC, ciliakas commented on SmartSaver/DataManagement/MonthlyUpdater.cs
> +        }
Fair enough

2020-10-18 17:18 UTC, ciliakas commented on SmartSaver/DataManagement/MonthlyUpdater.cs
> +                UpdateMonthlyIncome(entry, differenceInMonths, userId);
Maybe there should a an if statement here, not to run the update if the entry month is the same as current month or month in advance, because at the moment I found after some testing that it adds a copy (with IsMonthly = false) to the next month

2020-10-19 07:20 UTC, ciliakas requested changes
The DifferenceInMonths method is very tidy and works well, however in our case we do care if one date is in advance of the other, because in one case we have to add the entries and in other case we shouldn't.

2020-10-19 07:20 UTC, ciliakas commented on SmartSaver/utilities/TimeManager.cs
> +
So I'm still having issues with duplicate entries, and I think it's because the difference in months is always positive, as such even if we have a month in advance, Monthly Updater will still add another entry, even though it shouldn't.

2020-10-19 07:21 UTC, Stokalas commented
Since I liked @ciliakas solution to duplicate bug more, I changed and pushed, since he closed his pull request, so just giving credit 🙂

2020-10-19 07:25 UTC, Stokalas commented on SmartSaver/utilities/TimeManager.cs
> +
Changed this method to not have absolute value

2020-10-19 11:40 UTC, ciliakas approved these changes
Changing the DifferenceInMonths method seems to have fixed the last bug, everything seems to be working perfectly now. Good job 👍

2020-10-19 11:40 UTC, ciliakas commented on SmartSaver/utilities/TimeManager.cs
> +
After this change everything seems to be working fine, I tested going a few months back, the current month and month into the future and there's no faults 👍

2020-10-19 18:17 UTC, merged