Requirements v1
MatasLa/SmartSaver pull request #47
Opened 2020-10-21 08:37 UTC by Stokalas

Resharping and fixes in a lot of files.
**Most attention should be paid:** 
- DataFilter.cs
- ImportanceGroup.cs

2020-10-21 19:33 UTC, ciliakas reviewed
Overall looks good, but I do have some questions I raised in the comments

2020-10-21 19:33 UTC, ciliakas commented on SmartSaver/utilities/InternetParser.cs
> -                var pricestr = productListItems[0].Descendants("span").FirstOrDefault(node => node.GetAttributeValue("class", "")
Maybe there is a better name for this variable? Seems out of place in our code style

2020-10-21 19:33 UTC, ciliakas commented on SmartSaver/DataManagement/DataFilter.cs
Again can't comment, but  on line 15 'this' is unnecessary

2020-10-21 19:33 UTC, ciliakas commented on SmartSaver/DataManagement/DataFilter.cs
> +using System.Diagnostics;
This directive can be removed

2020-10-21 19:33 UTC, ciliakas commented on SmartSaver/DataManagement/DataFilter.cs
> +            return _data.Expenses.Where(x => (x.Date.Year == dateTime.Year) && (x.Date.Month == dateTime.Month))
There are a lot of redundant parentheses in this file, though I do see how it can be argued they improve readability

2020-10-22 13:06 UTC, DeividasLT5 commented on SmartSaver/Authentication/UserAuth.cs
> +            if (userInfo == null) return false;
I would use brackets, just to keep the style of "if" identical everywhere, also if for some reason you need to insert statements into the if, there already being brackets makes it just that little bit easier, therefore i believe its the better standard

2020-10-22 13:46 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataFilter.cs
> +                                }).ToList();
This seems like some very weird style. Wouldn't it be better to try and fit it into a couple lines, instead of a whole block?

2020-10-22 13:48 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataFilter.cs
> +                    .ToList();
Are these line breaks necessary?

2020-10-22 15:21 UTC, MatasLa commented on SmartSaver/Authentication/UserAuth.cs
> +            if (userInfo == null) return false;
I also prefer to use brackets, since its makes code more readable.

2020-10-22 16:45 UTC, Stokalas commented on SmartSaver/Authentication/UserAuth.cs
>      public class UserAuth
Since Matas is responsible for this class, and as far as I know he can't use Resharper properly I resharped it, and that's it, but I will change it to static in next commit to fix all these problems 🙂

2020-10-22 16:46 UTC, Stokalas commented on SmartSaver/Authentication/UserAuth.cs
> +            if (userInfo == null) return false;
I think the one who did this bracketless `if`'s was resharper :') but I will change it.

2020-10-22 16:47 UTC, Stokalas commented on SmartSaver/DataManagement/DataJSON.cs
>  		/*Writing/reading JSON files*/
this was mainly left because before I wasn't using `_` before private variables. Thanks for noticing 🙂

2020-10-22 16:52 UTC, Stokalas commented on SmartSaver/DataManagement/DataFilter.cs
> +            return _data.Expenses.Where(x => (x.Date.Year == dateTime.Year) && (x.Date.Month == dateTime.Month))
I think I'll leave them since there are two conditions and to distinguish between them is much easier when these parentheses are there.

2020-10-22 16:52 UTC, Stokalas commented on SmartSaver/DataManagement/DataFilter.cs
> +                                }).ToList();
This was written very carefully by "copying" what's in MS Docs, so I kept that style.

2020-10-22 16:53 UTC, Stokalas commented on SmartSaver/DataManagement/DataFilter.cs
> +                                }).ToList();
And somewhy here line `(importance, entries) =>` is a bit off to the right, but in Visual studio it is alligned perfectly to the lines above it.

2020-10-22 16:54 UTC, Stokalas commented on SmartSaver/DataManagement/DataFilter.cs
> +                    .ToList();
It was chopping done by resharper to increase readability.

2020-10-24 16:51 UTC, ciliakas requested changes
Thinks look good, but I have some comments that I would like to be addressed

2020-10-24 16:51 UTC, ciliakas commented on SmartSaver/Authentication/UserAuth.cs
> +            }
The style in 22 is inconsistent with the rest of the file, also would suggest is null, looks better in my opinion :) (even though it functionally the same)

2020-10-24 16:51 UTC, ciliakas commented on SmartSaver/Authentication/UserAuth.cs
>              var rand = new Random();
Random size on line 83 is hard coded, as well as the SmtpClient string on line 91, Port on line 94 , and Salt size on lines 25 and 60. I know at the moment most of these only occur once but it's better practice to have these as variables.

2020-10-24 16:51 UTC, ciliakas commented on SmartSaver/utilities/ArrayExtension.cs
> +                Array.Copy(source, index + 1, dest, index, source.Length - index - 1);
Correct me if I'm wrong, but I think this doesn't match our 'if' statement style

2020-10-24 16:51 UTC, ciliakas commented on SmartSaver/DataManagement/QueueList.cs
> +        public QueueList(int size = 5)//default size for queue 5
Probably would be good to declare a public static constant max goal list size, maybe in Goal.cs, for easier changing in the future

2020-10-24 16:51 UTC, ciliakas commented on SmartSaver/DataManagement/DataFilter.cs
>                                      Importance = importance.ToString(),
Why are we using importance as a string insteead of the Importance enum?

2020-10-24 18:14 UTC, Stokalas commented on SmartSaver/DataManagement/QueueList.cs
> +        public QueueList(int size = 5)//default size for queue 5
The thing is that this queue is not used for goals, as we are not using it to store goals, no point in delcaring such value

2020-10-24 18:16 UTC, Stokalas commented on SmartSaver/DataManagement/DataFilter.cs
>                                      Importance = importance.ToString(),
Simply just because class is storing it as String, it could be stored as int, but since array is ordered by importance, for this instance even that int or string is unneeded. But if you would like to see int stored, answer to this comment.

2020-10-24 18:16 UTC, Stokalas commented on SmartSaver/utilities/ArrayExtension.cs
> +                Array.Copy(source, index + 1, dest, index, source.Length - index - 1);
That's a bit of code which I copied, and prob missed this part of ifs :D thanks

2020-10-25 06:05 UTC, ciliakas commented on SmartSaver/DataManagement/QueueList.cs
> +        public QueueList(int size = 5)//default size for queue 5
Sorry, it was late in the evening and I mixed up what QueueList is used for :D So is the default size 5 because it's how many Importance options we have?

2020-10-25 06:07 UTC, ciliakas commented on SmartSaver/DataManagement/QueueList.cs
> +        public QueueList(int size = 5)//default size for queue 5
Sorry, it was late in the evening and I mixed up what QueueList is used for :D So is the default size 5 because it's how many Importance options we have?

2020-10-25 06:07 UTC, ciliakas commented on SmartSaver/DataManagement/DataFilter.cs
>                                      Importance = importance.ToString(),
I think it would make more sense for the ImportanceGroup class to save it as an int or enum

2020-10-25 06:09 UTC, ciliakas commented on SmartSaver/DataManagement/DataFilter.cs
>                                      Importance = importance.ToString(),
I think it would make more sense for the ImportanceGroup class to save it as an int or enum

2020-10-25 06:11 UTC, ciliakas commented on SmartSaver/DataManagement/DataFilter.cs
>                                      Importance = importance.ToString(),
I think it would make more sense for the ImportanceGroup class to save it as an int or enum

2020-10-25 13:38 UTC, Stokalas commented on SmartSaver/DataManagement/QueueList.cs
> +        public QueueList(int size = 5)//default size for queue 5
Well if we used it for goals it could be max 5 goals, and 5 importances, so I picked 5 as default, but when creating such queueList you can set any amount, it is in part to fulfill optional arguments requirement.

2020-10-25 17:52 UTC, ciliakas approved these changes
All issues that were raised are solved.

2020-10-25 18:04 UTC, merged