Data rework
MatasLa/SmartSaver pull request #48
Opened 2020-10-23 12:47 UTC by Stokalas

Split of method for local lists and database entries

2020-10-23 12:51 UTC, Stokalas reviewed
As I'm one of the authors of the change, I've just review file which was created by Matas

2020-10-23 12:51 UTC, Stokalas commented on SmartSaver/DataBase/DatabaseUpdate.cs
> +        }
Was needed method, but probably unnecesary since we are changing how goals are saved in queue

2020-10-23 12:51 UTC, Stokalas commented on SmartSaver/DataBase/DatabaseUpdate.cs
> +		{
brackets out of place

2020-10-23 12:51 UTC, Stokalas commented on SmartSaver/DataBase/DatabaseUpdate.cs
> +		{
same problem with brackets

2020-10-23 16:53 UTC, DeividasLT5 commented on SmartSaver/DataManagement/Data.cs
> +            if (goal != null) GoalsList.Remove(goal);
If brackets missing, breaks our standard

2020-10-23 16:53 UTC, DeividasLT5 commented on SmartSaver/DataManagement/Data.cs
> +            if (income != null) Income.Remove(income);
If brackets missing, breaks our standard

2020-10-23 16:53 UTC, DeividasLT5 commented on SmartSaver/DataManagement/Data.cs
> +            if (dataEntry != null) Expenses.Remove(dataEntry);
If brackets missing, breaks our standard

2020-10-23 16:53 UTC, DeividasLT5 commented on SmartSaver/DataManagement/Data.cs
> +            if (temp == null) return false;
If brackets missing, breaks our standard

2020-10-23 16:54 UTC, DeividasLT5 commented on SmartSaver/DataManagement/Data.cs
> +            if (temp == null) return false;
If brackets missing, breaks our standard

2020-10-23 16:54 UTC, DeividasLT5 commented on SmartSaver/DataManagement/Data.cs
> +            if (temp == null) return false;
If brackets missing, breaks our standard

2020-10-23 16:54 UTC, DeividasLT5 commented on SmartSaver/DataManagement/Data.cs
> +            if (temp == null) return false;
If brackets missing, breaks our standard

2020-10-24 08:31 UTC, Stokalas commented on SmartSaver/DataManagement/Data.cs
> +            if (goal != null) GoalsList.Remove(goal);
Good point, I'll fix it on requirementsv1 branch

2020-10-24 10:30 UTC, DeividasLT5 approved these changes
Other than the if brackets missing and not fitting our standard, everything seems good. Brackets were promised to be changed in another branch, so i don't see any further issues

2020-10-24 17:05 UTC, ciliakas commented on SmartSaver/DataBase/DatabaseUpdate.cs
> +            if (temp != null)
I would suggest changing all of the occurences of this line of into 
if( temp != null) return 
or atleast
if( temp != null) 
{
return something
}
to reduced unnecessary nesting and improve readability

2020-10-24 18:05 UTC, ciliakas commented on SmartSaver/DataBase/DatabaseUpdate.cs
> +    public class DatabaseUpdate
The name left me a bit confused for a moment, maybe it should be renamed to something more clear, like DatabaseUpdate**r**

2020-10-24 18:07 UTC, ciliakas requested changes
Some errors in style are left in here, also this is based on a quite old version of dev so it needs to be updated.

2020-10-25 18:00 UTC, ciliakas commented on SmartSaver/DataManagement/Data.cs
> +            var newGoal = new Goal(title);
This doesn't compile because Goal does not have such constructor

2020-10-25 18:00 UTC, ciliakas commented on SmartSaver/DataManagement/Data.cs
> +            var newGoal = new Goal(title, value) {Id = id};
This does not compile because Goal does not contain such constructor

2020-10-25 18:51 UTC, Stokalas commented
I have solved merge conflicts.

2020-10-25 19:28 UTC, ciliakas approved these changes
The issues that were raised have been resolved, and the code readability now is much improved.

2020-10-25 19:30 UTC, merged