Calculations
MatasLa/SmartSaver pull request #49
Opened 2020-10-24 16:44 UTC by DeividasLT5

Reworked previous smart calculation into a general saving one and added a smarter saving method.

2020-10-24 18:45 UTC, ciliakas requested changes
There are many things to note, so I created a pull request with my version of this branch with all of the suggestions that I have

2020-10-24 18:45 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
> +        private const decimal _minimalSavingValue = 0.1M;
Sorry I gave you the wrong info here - private const variables should be named as follows '**S**avingChoce'

2020-10-24 18:50 UTC, Stokalas reviewed
I've just left suggestion for acquiring certain importance entries, and since I saw another pull request of refactored version of this code, I did not pay attention to minor details

2020-10-24 18:50 UTC, Stokalas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                List<DataEntry> expenses = dataFilter.GetExpenses((Importance)i);
I would suggest to use Grouping by importance here since it would return array with all the importances.

2020-10-26 11:09 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataCalculations.cs
> +                List<DataEntry> expenses = dataFilter.GetExpenses((Importance)i);
Yes, I agree and already did so :D

2020-10-26 12:22 UTC, Stokalas requested changes
Left a notice, And another thing, since this part of code is kinda complicated compared to other, it would be nice to see atleast general comments about what which part is doing, since it could be hard to remember after about a month :)

2020-10-26 12:22 UTC, Stokalas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                var expenses = groupedByImportance[i].Entries;
This loop wont work since it goes from 1 to 5 and array stores elements from 0 to 4, easiest fix would be to -1 from `(int)Importance.Unnecessary` and `(int)Importance.High`

2020-10-26 14:04 UTC, Stokalas approved these changes
The problems seems to have been fixed, well done. Just one question 🙂

2020-10-26 14:04 UTC, Stokalas commented on SmartSaver/forms/finances/goals/ExpandedGoalForm.cs
> +        [SuppressMessage("ReSharper", "PossibleNullReferenceException")]
This thing is weird, what is it for?

2020-10-26 15:45 UTC, ciliakas commented on SmartSaver/forms/finances/goals/ExpandedGoalForm.cs
> +        [SuppressMessage("ReSharper", "PossibleNullReferenceException")]
It suppresses the error message about possible exception. I  use it because these columns will definitely be there because of the table constructor. However maybe we should implement some kind of error checking here.

2020-10-26 15:56 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
> +        public bool GetSuggestedExpensesOffers(List<DataEntry> entryList, Goal goal, SavingType savingType, List<EntrySuggestion> offerList)
offerList should be renamed to entrySuggestions or something like that

2020-10-26 15:57 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
>          }
I don't think method is necessary

2020-10-26 15:58 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
>                      AddToExpensesOfferList(entry, amountAfterSaving, offerList);
This method can just be replaced by : 

                    offerList.Add(new EntrySuggestion(entry, amountAfterSaving));

2020-10-26 15:59 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
Should probably delete the old commented code here, if need be we can always find it in our commits and it's not too complex anyways

2020-10-26 16:01 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
> -        private bool ImportanceBasedCalculation(DataEntry data, decimal importanceBasedSavingRatio, EntryType entryType)
This method always return true, so I don't think that makes much sense, also code could be simplified by removed the calculation for Incomes since we are not planning to use it anyways (we can always find it in our old commits if we ever need it, and now this code looks messy for our examination)

2020-10-26 16:02 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
>          }
It is debatable if these methods are necessary, as each can be replaced with one line of code, like I commented before.

2020-10-26 16:03 UTC, ciliakas requested changes
Code works, however I don't think it's in the best shape it could be to present it

2020-10-26 16:08 UTC, MatasLa requested changes
Code works fine, however I agree with Arnas about improvements.

2020-10-27 12:55 UTC, Stokalas approved these changes

2020-10-27 12:55 UTC, Stokalas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                var ratio = (int) Importance.Unnecessary - i;
Nice addition since now we're not that important on `i`, and by reverting it we can use differently sorted importances

2020-10-27 12:55 UTC, Stokalas commented on SmartSaver/DataManagement/DataCalculations.cs
> +        private static void AddToExpensesOfferList(DataEntry entry, decimal amountAfterSaving, ICollection<EntrySuggestion> entrySuggestions)
Just out of curiosity, what are benefits or why ICollection is used here?

2020-10-27 13:03 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataCalculations.cs
> +                var ratio = (int) Importance.Unnecessary - i;
Agreed

2020-10-27 13:04 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataCalculations.cs
> -            //}
In retrospect this code wasn't worth keeping, as you said before, even if we need it, previous commits exist, deleting it tidies up the code :)

2020-10-27 13:10 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataCalculations.cs
>                      }
A good use of the default case, didn't think about this, good job :)

2020-10-27 13:25 UTC, DeividasLT5 reviewed
I agree with all of the improvements made, so won't comment on every single one. I think this code should be ready to pull now

2020-10-27 13:25 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
> +        private static void AddToExpensesOfferList(DataEntry entry, decimal amountAfterSaving, ICollection<EntrySuggestion> entrySuggestions)
It is a more general type, it gives us more freedom usedifferent sort of Collection types

2020-10-27 13:31 UTC, ciliakas approved these changes
Obviously I approve since I made the changes myself

2020-10-27 13:31 UTC, merged