Calculations refactoring
MatasLa/SmartSaver pull request #50
Opened 2020-10-24 18:44 UTC by ciliakas

These are my suggestions on how to improve DataCalculations class, along with some auto fixes by resharper. Please let me know what you think

2020-10-24 18:59 UTC, Stokalas requested changes
I really like the changes made by refactoring, and overall changes in the logic of calculations. I just left some suggestions and questions which I woud really like to see implement/answered 🙂

2020-10-24 18:59 UTC, Stokalas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                foreach (var entry in expenses)
Same here, I think that groupJoining function in dataFilter should be used here.

2020-10-24 18:59 UTC, Stokalas commented on SmartSaver/DataManagement/EntrySuggestion.cs
> +        }
Why is the empty constructor needed here? Since if we don't have any data we will not create such object at all?

2020-10-24 18:59 UTC, Stokalas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                              break;
So we're creating income offer lists after all? The if we move to the groupJoin method I mentioned before, we need same grouping for income?

2020-10-25 05:41 UTC, ciliakas commented on SmartSaver/DataManagement/EntrySuggestion.cs
> +        }
Good point, removed empty constructor

2020-10-25 06:11 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                foreach (var entry in expenses)
I think dev still doesn't have the groupJoining function in it, but I do agree it's what should be used here once we pull that request

2020-10-25 06:12 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                foreach (var entry in expenses)
I think dev still doesn't have the groupJoining function in it, but I do agree it's what should be used here once we pull that request

2020-10-25 06:13 UTC, ciliakas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                              break;
I only refactored this code with resharper, I didn't want to remove the established code if we needed it in the future for some reason.
Though I do agree probably we won't need these calculations for income

2020-10-25 13:40 UTC, Stokalas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                              break;
Well then I guess it should be commented (deletion is not the best choice), to point that it is not used.

2020-10-25 13:41 UTC, Stokalas commented on SmartSaver/DataManagement/DataCalculations.cs
> +                foreach (var entry in expenses)
So as I understand that we will use it just after it gets merged into dev. And with this all my concerns are dealt with and I'm approving this pull request :)

2020-10-25 13:41 UTC, Stokalas approved these changes

2020-10-26 08:15 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataCalculations.cs
> +                foreach (var entry in expenses)
I checked the function out and i thing it fits really well, will integrate

2020-10-26 08:18 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataCalculations.cs
> +                              break;
yeah, I implemented the income part quite some time ago, but I guess its time to comment it out, as we're not going to be using it

2020-10-26 08:23 UTC, DeividasLT5 approved these changes
Thanks for using resharper to tidy up the code, as my computer really doesn't like it installed and I can barely work with it enabled. As for the OfferData rename, I approve, feels clearer than what I had.

2020-10-26 08:26 UTC, merged

2020-10-26 08:37 UTC, DeividasLT5 commented
Also forgot to mention that i really like the your ChoosingImportance method optimisation :)

2020-10-26 09:57 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataCalculations.cs
> +            //Since at the moment you have the ratios set as nearly the Enum values, i switched to a shorter return expression
Good point

2020-10-26 10:06 UTC, DeividasLT5 commented on SmartSaver/DataManagement/DataCalculations.cs
> +        // ImportanceBasedCalculation always returns true, doesn't really make sense for a method to always return true
Its part of a bigger system, and this part essentially can't decide if the thing is false by itself, but it does seem weird, I might try changing it at some point